openapi: 3.1.0
info:
  version: 1.0.0
  title: Contact Book API
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: |
    This is the API documentation for the Contact Book application.

tags:
  - name: contacts
    description: Everything about contacts

servers:
  - url: http://localhost:3000
  - url: https://contacts-app-szep.onrender.com

paths:
  /contacts:
    get:
      $ref: ../swagger/paths/contacts/get.yaml
    post:
      $ref: ../swagger/paths/contacts/post.yaml

  /contacts/{contactId}:
    get:
      $ref: ../swagger/paths/contacts/{contactId}/get.yaml
    patch:
      $ref: ../swagger/paths/contacts/{contactId}/patch.yaml
    delete:
      $ref: ../swagger/paths/contacts/{contactId}/delete.yaml

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
  schemas:
    Contact:
      $ref: ../swagger/components/schemas/Contact.yaml
    ApiResponse:
      $ref: ../swagger/components/schemas/ApiResponse.yaml
    PaginatedContacts:
      $ref: ../swagger/components/schemas/PaginatedContacts.yaml
    ErrorResponse:
      $ref: ../swagger/components/schemas/ErrorResponse.yaml
